### ISSUE TITLE
[10k]: Brand identity, marketing, and communications audit

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1120]
### Definition

Initiating the data collection phase to inform the initial internal/external synthesis that will inform branding efforts. Gathering metrics, user engagement, feedback, and relevant data from various sources, such as newsletters, grantor communications, research findings, legacy brand documentation, etc. 

### Business Goals

- Complete audit of current brand landscape using collateral, brand standards, marketing materia, social media, data, and other relevant sources 
- Complete audit of competitor and similar organizations’ brand identities 
- Consolidate data in a shared repository or folder for collaborative access and synthesis 
- Analyze the current brand with a thorough audit and define a clear brand position that is aligned with organizational goals. These efforts inform the design of the brand identity

### In scope

- Audit 
- Findings presentation

### Out of scope

- {Item that is out of scope for this work}

### Tasks

- [x] Gather all the internal audit material listed below 
- [x] Gather external compset audit material listed below into folders 
- [x] Organize into the correct folders 
- [x] Create virtual audit board in Mural for internal and external 
- [x] Synthesize current messaging (email metrics, voice and tone guides for chat bot, blog posts, videos, etc) in order to inform positioning phase work 
- [ ] Nice-to-have: Conduct interviews with Grants stakeholders on the key shortcomings of the brand and marketing materials 
- [ ] Nice-to-have: Create prime/clients PAC with a list of people in the approval chain 
- [x] Create audit readout and preview with prime/clients

### Definition of Done

- [x] Audit board in Mural which includes an audit of the current brand landscape, including internal and external components with a readout shared with key stakeholders
- [x] Audit key findings document, such as Mural
- [x] Audit key findings review with stakeholders

**Comment by sumiat** [comment]
closing this! we shared the brand audit: https://app.mural.co/t/nava4113/m/nava4113/1706120999381/1557391ee8c021278eff19a543f9fde2a679a41c?sender=senongoakpem5792
