### ISSUE TITLE
[10k]: Primary and secondary brand audience identification

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1121]
### Definition

Starting with a deep look at all the audience info and internal/external user groups, we can then define the different audiences for the brand and potentially the language/outreach/identity needs they have.

The brand identity will not only be the specific users of grants.gov. It will be policymakers, members of the media, and internal HHS/Grants staff who work on the product. The new brand will need to account for their needs and focus as stakeholders.

### Business Goals

- Define the primary and secondary brand audiences for Grants
- Define how we engage with those responsible for governance internally

### In scope

- List of approved primary and secondary audiences (including stakeholders and key governance staff)

### Out of scope

- {Item that is out of scope for this work}

### Tasks

- [x] In addition to the four user groups (Huge), research people who are responsible for the brand, managing, and approving. 
- [x] Run working session to review and align on the research findings
- [ ] Audience list reviewed and approved by client

### Definition of Done

- [ ] List of approved primary and secondary audiences (including stakeholders and key governance staff)

**Comment by widal001** [comment]
Closing because issue was marked as 'Done' in https://github.com/orgs/HHS/projects/13
