### ISSUE TITLE
[10k]: Brand positioning, characters, and behaviors

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1122]
### Definition

Develop and iterate on the brand positioning statement. From there, develop and iterate on the brand characters and behaviors.
- Brand Characters: The combination of five distinct characteristics that we share as an organization. We demonstrate them through our behaviors.
- Brand Behaviors: Short actionable statements that interpret our characteristics into clear guidance for how we look, speak and act. They guide anyone representing Grants – through design, in writing, or in person

### Business Goals

- Define the what the key differentiators and brand position is for grants in the wider ecosystem. 
- Define, iterate on, and finalize a set of five of brand characters and their behaviors

### In scope

- Brand characters and behaviors workshop and presentation of findings

### Tasks

- [x] Research exercise with four applicant archetypes (e.g. "What are three words to describe Grants.gov?") 
- [x] Workshop with users - three words you want to use to describe your experience with Grants
- [x] Workshop with HHS stakeholders - three words you want to use to describe your experience with Grants
- [x] Draft brand characteristics and behaviors options, how they would be used (look, act, speak)
- [x] Characteristics/behaviors feedback and approval  

### Definition of Done

- [x] Brand characters and behaviors workshop 
- [x] Brand characters and behaviors presentation

**Comment by senongo** [comment]
this can be moved to complete
