### ISSUE TITLE
[10k]: Develop key messages

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1123]
### Definition

Create compelling, memorable, and consistent messaging that effectively communicates Grants.gov identity and unique value. Key messages define what the Grants.gov stands for, its personality, and the key benefits it offers to its audience. We’ll craft these statements by conducting research with the PAC so that messages resonate with our target audiences. 

### Business Goals

- Develop the value proposition for the brand
- Develop a set of compelling, memorable statements that can be used across audience types 
- Test and develop 2-3 key messages for each audience type

### In scope

- Voice and tone workshop with findings that focuses on how we speak 
- Define value proposition and key messages 
- Review of key messages and voice and tone guide

### Out of scope

- {Item that is out of scope for this work}

### Tasks

- [ ] Write value prop drafts 
- [ ] Get feedback from Grants stakeholders and audience 
- [ ] Draft voice and tone guide, share with stakeholders for feedback. Expect 3 rounds. 
- [ ] Write key message drafts 
- [ ] Finalize both value proposition and key messages, with examples of how to apply them across channels

### Definition of Done

- [ ] How we speak workshop  to define value proposition and key messages 
- [ ] Review of key messages and voice and tone guide

**Comment by widal001** [comment]
Replacing our old 10k ft deliverable issues with a new Epic format

**Comment by widal001** [comment]
Reopening for review during sprint planning
