### ISSUE TITLE
[10k]: Develop visual concepts

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1124]
### Definition

A set of activities that use the audit, brand behaviors, and key messaging frameworks to collaboratively develop 2 visual directions. The tasks are focused on getting feedback and participation from a wide variety of stakeholders and using activities to focus the team on how the mission gets represented visually

### In scope

- Involve stakeholders in the visual brainstorming process 
- Develop 2 visual directions for selection by stakeholder

### Out of scope

- {Item that is out of scope for this work}

### Tasks

- [x] User interviews and visual concept testing with PAC and external stakeholders
- [x] Visual Directions Workshop 
- [ ] Version 1 of logo, colorways, illustration and photography rules, typography 

### Definition of Done

- [x] Visual Directions Workshop 
- [ ] Final Visual Direction

**Comment by widal001** [comment]
Replacing our old 10k ft deliverable issues with a new Epic format

**Comment by widal001** [comment]
Reopening for review during sprint planning
