### ISSUE TITLE
[10k]: Develop visual identity system

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1125]
### Definition

Develop a final brand identity and all the associated assets, templates, and guidelines

### In scope

- Deliver a final brand guidelines and all the associated assets and rules
- Gain alignment from all key stakeholders on the brand direction 

### Out of scope

- {Item that is out of scope for this work}

### Tasks

- [ ] Final logo concept with knockout, color, reduced versions 
- [ ] Final typography rules for site and communications 
- [ ] Final illo and photography rules 
- [ ] Create digital brand guidelines 
- [ ] Digital assets and production templates (websites, social media, etc) 
- [ ] Marketing and communications assets and production templates (decks, emails, one-pagers, business cards, letterhead, etc)
 

### Definition of Done

- [ ] Final Visual Identity System, including color, typography, logo, templates, assets, comms materials, illustrations and photography) 
- [ ] Final brand identity presentation

**Comment by widal001** [comment]
Replacing our old 10k ft deliverable issues with a new Epic format

**Comment by widal001** [comment]
Reopening for review during sprint planning

**Comment by mxk0** [comment]
Closing as this already happened.

**Comment by widal001** [comment]
Beep boop: Automatically setting the point and sprint values for this issue in project HHS/13 because they were unset when the issue was closed.
