### ISSUE TITLE
[10k]: Email marketing

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1126]
### Definition

Developing a new strategy, voice, tone, and style guide for Grants.gov newsletter audience of TKNUMBER with a goal of using this communication channel to raise engagement with Grants.gov, with an emphasis on growing engagement with audiences that are typically underrepresented in the Grants application. 

### Business Goals

- Increase engagement with newsletter audience
- Grow applicant stream from groups traditionally underrepresented from the applicant pool
- Communicate changes to the application system
- Help people navigate the complex application process
- Disseminate information about available grants
- Consider methods to prevent grant fraud

### In scope

- Email personas
- Establish success metrics
- Establish voice, tone, and style
- Email marketing strategy

### Tasks

- [ ] Audit newsletters and blog posts, social posts, etc
- [ ] Review audience/behavior analytics
- [ ] Develop email personas
  - [ ] Use existing user research
  - [ ] Bring additional questions to the PAC
  - [ ] Use audience/behavior analytics
- [ ] Establish success metrics
  - [ ] Use audience/behavior analytics and see what’s performing and what’s not
  - [ ] Work with stakeholders to establish what metrics we want to highlight
  - [ ] Use audience/behavior analytics to establish baseline
- [ ] Establish voice, tone, style 
  - [ ] Sync with editorial team to learn more about existing voice/tone/style
  - [ ] Develop voice and tone guidelines
- [ ] Develop email marketing strategy
  - [ ] Sync with editorial team to align on editorial calendar
  - [ ] Work with branding on any design changes
  - [ ] Align with stakeholders on strategy
  - [ ] Establish editorial process
    - [ ] Writing, editing process
    - [ ] Publication process
    - [ ] Stakeholder approvals
- [ ] Implement strategy
  - [ ] Write/edit changes to newsletter
- [ ] Test strategy
  - [ ] Continue conducting analysis to measure success
  - [ ] Iterate based on data

### Definition of Done

- [ ] Create email personas 
- [ ] Establish success metrics
- [ ] Establish voice, tone, style
- [ ] Create and share email marketing strategy internally for approval
- [ ] Implementation and testing of strategy

**Comment by widal001** [comment]
Replacing our old 10k ft deliverable issues with a new Epic format

**Comment by widal001** [comment]
Reopening for review during sprint planning
