### ISSUE TITLE
[10k]: Staging environment

### ISSUE THREAD

**Issue by coilysiren** [HHS/simpler-grants-gov#1273]
### Definition

Configure a staging environment that deploys consistently off our `main` branch, and can be relied upon over time.

### Business Goals

- All users, including product, HHS staff, and design, can test changes in staging before the changes go into production 
- We have a staging environment that reliably and automatically deploys from our baseline configuration
- The dev environment is freed up for ad-hoc deployments and testing

### In scope

- deploying every part of our terraform configuration to staging, not just the two folders that are being deployed now (`infra/frontend/service` and `infra/api/service`)
- configuring the FDW (foreign data wrapper) so data is flowing into the staging API
- changing our behaviors and documentation to rely on `staging` instead of `dev`

### Out of scope

- deploying multiple dev environments
- deploying preview builds
- any of the other stretch goals described in this related ADR: https://github.com/HHS/simpler-grants-gov/pull/1091

### Tasks

- [x] https://github.com/HHS/simpler-grants-gov/issues/1267
- [x] https://github.com/HHS/simpler-grants-gov/issues/1288
- [x] https://github.com/HHS/simpler-grants-gov/issues/1291
- [x] https://github.com/HHS/simpler-grants-gov/issues/1290

**Comment by widal001** [comment]
Replacing our old 10k ft deliverable issues with a new Epic format

**Comment by widal001** [comment]
Reopening for review during sprint planning
