### ISSUE TITLE
[10k]: Open source onboarding - Communications for limited outreach

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#1320]
### Definition

Create and manage the communications needed to support a targeted announcement to key stakeholders about the Open source onboarding deliverable. See this issue #72 for more details.

### Business Goals

- Keeping internal stakeholders informed about our plans to onboard open source contributors to the project
- Beginning to invite trusted open source contributors to our public communication channels

### In scope

- Preparing a presentation or updates to key internal stakeholders about this deliverable
- Drafting and approving communications for a limited outreach to trusted open source partners

### Out of scope

- A public announcement or email blast to all of the members on our listserv. Our initial round of recruitment for the open source initiative will be limited to trusted partners.

### Tasks

- [ ] {List the tasks that should be completed with this deliverable}

### Definition of Done

- [ ] The following internal stakeholders have been notified about the onboarding process and strategy prior to inviting external stakeholders to join our open source initiative:
  - [ ] TODO
- [ ] The content of the limited announcement has been approved by the following stakeholders
  - [ ] TODO
- [ ] A limited announcement (most likely email) has been set to _trusted_ members of the following stakeholder groups inviting them to test out our new API:
  - [ ] Open Source at CMS
  - [ ] [US Digital Response (USDR)](https://www.usdigitalresponse.org/)
