### ISSUE TITLE
[10k]: Search UI: feature flags, API, and infrastructure

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1487]
### Description

Feature flag and infrastructure work to support the Search UI

### Business Value & Description

See: [Search UI public deliverable](https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/product/deliverables/specifications/search-user-interface#business-value).

### User Stories

See: [Search UI public deliverable](https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/product/deliverables/specifications/search-user-interface#business-value).

### Sub-Tasks

See https://github.com/HHS/simpler-grants-gov/milestone/134

### Definition of Done

- [x] Feature flags enabled on search page and for the site
- [x] Functionality can be hidden from users behind a URL-based feature flag, if desired
- [x] All of the search features available in the UI are also available via the API, and vice versa
- [ ] Any site downtime will generate automated notifications to project maintainers

Nice-to-have:

- [ ] Method to sort by relevance

**Comment by rylew1** [comment]
@acouch @andycochran  - should the below 2 items be moved to their own ticket? Then we can close this?

```
 Any site downtime will generate automated notifications to project maintainers
Nice-to-have:

 Method to sort by relevance

```

**Comment by widal001** [comment]
Replacing our old 10k ft deliverable issues with a new Epic format

**Comment by widal001** [comment]
Reopening for review during sprint planning

**Comment by mxk0** [comment]
Remaining work is covered by #2262 and #2264
