### ISSUE TITLE
Search UI - Analytics

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#1488]
### Description

Build the analytics for the search page on simpler.grants.gov

### Business Value & Description

See: [Search UI public deliverable](https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/product/deliverables/specifications/search-user-interface#business-value).

### User Stories

See: [Search UI public deliverable](https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/product/deliverables/specifications/search-user-interface#business-value).

### Sub-Tasks

See https://github.com/HHS/simpler-grants-gov/milestone/147

### Definition of Done

Data needed for metrics is actively being captured in PROD. Metrics described in [proposed metrics](https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/product/deliverables/specifications/search-user-interface#proposed-metrics) are delivered
- [x] Total number of searches made via the UI
- [x] Track search terms searched so that we can understand top search terms
- [x] Click-through-rate to the opportunity listing on grants.gov to measure the search accuracy for those top searched terms
- [x] Number of searches made per search term and the click conversion rate to the opportunity listing
- [x] Number of searches made per filter combination and the click-through-rate to the opportunity listing
- [x] Click-through-rate from search results to the opportunity listing

**Comment by widal001** [comment]
Replacing our old 10k ft issues with a new Epic format

**Comment by widal001** [comment]
Reopening for review during sprint planning

**Comment by mxk0** [comment]
Closing in favor of #2316
