### ISSUE TITLE
[placeholder]: Add GA4 tracking for search 

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#1881]
### Summary

**Blocked by the transformation work** 

We need to set up GA4 to track the following metrics: 

- [ ] Click-through-rate to the opportunity listing on grants.gov to measure the search accuracy for those top searched terms: this is to measure the metric: Click-through-rate to the opportunity listing on grants.gov to measure the search accuracy for those top searched terms; Aaron suggested possibly putting a # for each result? Might need to be a spike first
- [ ] Number of searches made per search term and the click conversion rate to the opportunity listing: might be the same  configuration as the first one: https://support.google.com/analytics/answer/1032321?hl=en#zippy=%2Cin-this-article
- [ ] Number of searches made per filter combination and the click-through-rate to the opportunity listing
- [ ] Click-through-rate from search results to the opportunity listing: i believe this should come standard - user searches > clicks on the search result to the opportunity listing

### Acceptance criteria

The following are captured and tracked in GA4
 - [ ]  Click-through-rate to the opportunity listing on grants.gov to measure the search accuracy for those top searched terms
 - [ ] Number of searches made per search term and the click conversion rate to the opportunity listing
 - [ ] Number of searches made per filter combination and the click-through-rate to the opportunity listing
- [ ] Click-through-rate from search results to the opportunity listing

**Comment by sumiat** [comment]
@btabaska will break this ticket up into smaller LOE

**Comment by btabaska** [comment]
Closed, placeholder has been swapped with tickets: https://github.com/HHS/simpler-grants-gov/issues/1892, https://github.com/HHS/simpler-grants-gov/issues/1891, https://github.com/HHS/simpler-grants-gov/issues/1890, https://github.com/HHS/simpler-grants-gov/issues/1889.
