### ISSUE TITLE
Search error logging

### ISSUE THREAD

**Issue by mxk0** [HHS/simpler-grants-gov#2375]
### Summary

To meet our quad 1 commitments for search, we need charting that allows us to prove:

> The monthly average error rate remains below 5%, meaning fewer than five 5xx errors per 100 API and five 5xx errors per 100 page requests in production.

### Acceptance criteria

- [x] Ticket to prove we have the needed API logging and charting (see [screenshot below](https://github.com/HHS/simpler-grants-gov/issues/2375#issuecomment-2403335424))
- [x] Ticket to prove we have the needed frontend logging and charting (#2633)
- [x] Ticket to screenshot API logging (at the end of the quad) (#2660)
- [x] Ticket to screenshot frontend logging (at the end of the quad) (#2660)

**Comment by coilysiren** [comment]
![Image](https://github.com/user-attachments/assets/efb7f903-b2aa-443c-ad2c-691e0b1165c0)

**Comment by mxk0** [comment]
We have the logging we need for the API. We can view these logs in CloudWatch today, and can use a future monitoring tool (e.g. NewRelic) in the future.

Still need to check what we have for the frontend.

**Comment by coilysiren** [comment]
https://docs.aws.amazon.com/opensearch-service/latest/developerguide/monitoring-pipeline-logs.html

**Comment by mxk0** [comment]
@mdragon do we have alerts like this in place already? (Copied from the acceptance criteria above.)

> Ticket to set alerts for error rates >5% (both API and frontend)

**Comment by mdragon** [comment]
Confirming we have the same level of detail for Frontend as they're both ELB and those natively report out their Target server and ELB level 5xx error metrics. ![Image](https://github.com/user-attachments/assets/9cdee9cc-01f7-4e7e-899d-42123a4dc95c)

**Comment by widal001** [comment]
Beep boop: Automatically setting the point and sprint values for this issue in project HHS/13 because they were unset when the issue was closed.
