### ISSUE TITLE
Search/Opportunity Listing v2 *

### ISSUE THREAD

**Issue by mxk0** [HHS/simpler-grants-gov#2875]
### Press release

The Simpler Grants.gov team recently delivered a revamped Search and Opportunity Listing with a simpler user experience, improved search relevancy, and easier-to-digest opportunity information. We received a lot of great feedback from the community on this initial release and are excited to announce a round of improvements we made based on your feedback. These improvements include usability fixes like making it easier to share a search, as well as solutions to common user needs like saving a search or saving an opportunity. Last but not least, we have a plan in place to make Simpler the default search for visitors to Grants.gov so that all users can experience the benefits of these improvements.

### Acceptance criteria

- [x] Users can save an opportunity and view/open/delete their saved opportunities (#3118, blocked by #2640)
- [x] Users can save a search and view/open/delete their saved searches (#3119, blocked by #2640)
- [x] Julius and Lucas signed off on a plan, developed with input from all teams including the HHS PMO, MicroHealth, BPS, Nava, and Agile Six, to make Simpler Search the default Grants.gov search by the end of Base Year 1. Plan includes: (#3638)
  - [x] Agreed upon release date for when the Search tab on existing Grants.gov will point to [simpler.grants.gov/search](http://simpler.grants.gov/search) (#4236)
  - [x] Load testing plan to ensure our infrastructure can handle all of Grants.gov’s traffic (#4238)
  - [x] Clear qualitative criteria for when we think the Simpler Search UX is ready for 100% of traffic, including lists of features or fixes that are “must have” before promotion (#4337)
  - [x] A communications strategy to notify Grants.gov users about the upcoming change (#4236)

### Metrics

- [x] At least 500 saved opportunities are created by at least 50 unique users (#4616)
- [x] At least 250 searches are saved by at least 25 unique users (#4616)
- [x] Set a baseline for DAU, MAU, and DAU/MAU ratio including new instrumentation with a more-reliable analytics tool (e.g. New Relic) (#4240)

### Assumptions

- N/A

### Dependencies

- Saved searches and opportunity bookmarks both depend on #2640

**Comment by mxk0** [comment]
## Sprint 2.1 updates

**Status:** 🟢 On track

### Sprint goal

The main goals for this deliverable in Sprint 2.1 were to deliver working API endpoints for saved searches and saving opportunities, and design UI for both of those features.

### Accomplishments
- API endpoints delivered for saved searches and saved opportunities
- Design finalized for saved opportunities

### Rollover

- Design UI for saved searches

### Risks

- We don't see any large risks at this time.

### Sprint 2.2 Goals
- Deliver saved opportunities in dev
- Design UI for saved searches
- Draft recommendations for must-have Search/Opp Listing improvements

**Comment by mxk0** [comment]
## Sprint 2.2 updates

**Status:** 🟢 On track

### Sprint goal

The main goals for this deliverable in Sprint 2.1 were to deliver saving opportunities in dev, design the UI for saved searches, and draft recommendations for search usability improvements.

### Accomplishments
- Saving opportunities working locally
- Initial design for saved searches shared, feedback collected
- Initial design for search usability improvements shared, feedback collected

### Rollover

- Saving opportunities live in dev

### Risks

- We don't see any large risks at this time.

### Sprint 2.2 Goals
- Deliver saving opportunities in dev
- Deliver viewing saved opportunities on a developer machine
- Saved search UI finalized
- Design for next round of search usability improvements finalized

**Comment by mxk0** [comment]
## Sprint 2.3 updates

**Status:** 🟢 On track

### Sprint goal

The main goals for this deliverable in Sprint 2.1 were to deliver saving opportunities in dev, deliver viewing saved opportunities on a developer machine, finalize the saved search UI, and finalize the next round of search usability improvements.

### Accomplishments
- Saving opportunities in dev
- Saved search design finalized, implementation tickets created and prioritized for sprints 2.4/2.5
- Next round of search usability improvements finalized

### Rollover

- View saved opportunities on a developer machine

### Risks

- We don't see any large risks at this time.

### Sprint 2.4 Goals

- View saved opportunities live in dev
- Deliver ~50% of saved search on a developer machine
- Create implementation tickets for next round of search usability improvements

**Comment by mxk0** [comment]
## Sprint 2.4 and 2.5 updates

**Status:** 🟢 On track

### Sprint goal

The main goals for this deliverable in Sprint 2.4 and 2.5 were to deliver saved opportunities and saved search queries in our lower environments, and create tickets for the next round of search usability improvements.

### Accomplishments
- Save opportunities and view saved opportunities live in lower environments (blocked by Login.gov)
- Save a search query live in lower environments (blocked by Login.gov). Doesn't include viewing a list of saved searches.
- Next round of Search usability improvements ticketed and ready for dev

### Rollover

- View a list of your saved searches

### Risks

- Saved opportunities and saved search queries are both blocked by Login.gov

### Sprint 2.6 Goals

- Saved search queries feature complete in lower environments

**Comment by lucasmbrown-usds** [comment]
@mxk0 @margaretspring -- the part of all this I'm most nervous about right now is "Julius and Lucas signed off on a plan, developed with input from all teams including the HHS PMO, MicroHealth, BPS, Nava, and Agile Six, to make Simpler Search the default Grants.gov search by the end of Base Year 1." 

I do think there's a lot of back-and-forth that will need to happen on this plan with the PMO, MH, etc, and it's best to leave a lot of time for that. With only two sprints left before proof-of-delivery, I'd love to see a more formal plan presented and reviewed with all parties, so we can agree on a launch date before Sept 9th 2025.

**Comment by chrisw-nava** [comment]
## Sprint 2.6 updates

**Status:** 🟢 On track

### Sprint goal

The main goals for this deliverable in Sprint 2.6 were to have saved search queries feature complete in the lower environments and an initial round of testing on the saved search and saved opportunities features.

### Accomplishments
- Saved search queries feature complete, including viewing a list of your saved searches 
- Initial round of testing on saved searches and saved opportunities complete, priority follow up items have been ticketed.
- Saved searches and saved opportunities now live in the "Workspace" nav in lower environments 

### Rollover

- N/A

### Risks

- N/A

### Sprint 2.7 Goals

- Finalize written plan for bringing Simpler search to Grants.gov
- Prioritized list of must-have Search V2 items based on completed research findings

**Comment by chrisw-nava** [comment]
## Sprint 2.7 updates

**Status:** 🟢 On track

### Sprint goal

The main goals for this deliverable in Sprint 2.7 were to finalize user feedback artifacts and prioritize them and complete our written plan for bringing Simpler search to Grants.gov

### Accomplishments
- User research observation sheet and prioritized list of must-have enhancements for Quad 3 are complete 
- Written plan for bringing Simpler search to Grants.gov has had an initial review and is ready for approval
- Prototype for user ability to download a .zip file of all opportunity documents is ready for demo on a developer machine 

### Rollover

- N/A

### Risks

- The timeline for accomplishing our metrics on this deliverable - 500 saved opportunities and 250 saved searches - will be tight for the official end of Quad 3 on May 8; however, the features will be complete and available to users

### Sprint 2.8 Goals

- Run async bug bash for auth, saved opportunities, and saved search queries
- High-priority issues that come out of bug bash are fixed
- Search as default document reviewed and finalized with HHS (carryover from 2.7)

**Comment by chrisw-nava** [comment]
## Sprint 2.8 updates

**Status:** 
 - Feature work: ✅  Complete 
 - Metrics: 🟡 At Risk, tracking closely

### Sprint goal

The main goal for this deliverable in sprint 2.8 was to complete a bug bash and fully launch the feature to production. This goal was met! 

### Accomplishments
- Bug bash completed and all remaining high priority issues resolved
- Launched into production 🚀 

### Rollover

- Remaining rollover is categorized under the Quad 3 deliverable: Promote Simpler Search #4571

**Comment by chrisw-nava** [comment]
## End of Quad Update

**Status:** 
 - Feature work: ✅  Complete 
 - Metrics: ✅  Complete 
 - All metrics and acceptance criteria have been met for this deliverable. I'm including a PDF export of the Dashboard as of 7:40a ET on May 7 2025 showing the saved queries, saved opportunities, and MAU/DAU information. This is also published [here](https://onenr.io/0MR2x28ZkQY) in New Relic. 

[Usage and User Metrcs - May 7 2025.pdf](https://github.com/user-attachments/files/20082960/Usage.and.User.Metrcs.-.May.7.2025.pdf)
