### ISSUE TITLE
[10k]: Communication implementation

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#302]
### Description

Implement chat, wiki, ticket tracking, calendar, email listservs, and email inboxes in a way that's accessible for all team members and the public.

- [x] #98 
- [x] #105 
- [x] #30 

### Sub-tasks
- [x] #379 
- [x] #98
- [x] #529 
- [x] #411  

### Definition of Done

- [x] The following conditions have been satisfied for all tools:
  - [x] At least 5 members of HHS full-time staff have been onboarded.
  - [x] At least 5 members of contractor teams (employed by HHS) have been onboarded.
  - [ ] At least 3 members of the general public have been onboarded - will be tracked in #1231 
  - [x] New users can be onboarded to the tool for no cost to the user in a process that takes less than 2 days.
  - [x] Services are accessible to all people on the HHS network, public internet, and *preferably* the White House network and most or all agency networks
  - [x] Onboarding instructions for new users are clearly and accessibly documented in a public place.
  - [x] Instructions for the internal team that assists with onboarding new users are clearly and accessibly documented in a public place.
  - [x] Code for managing and deploying these services is deployed to `main` & PROD (if necessary)
- [x] Ticketing system is live with the following conditions satisfied:
  - [x] At least 1 ticket has been created and assigned to an epic (or an equivalent concept).
  - [x] Without logging in, members of the public can see tickets that are being worked on.
  - [x] Default 'templates' have been created for tickets, epics, etc, that have the fields we've decided are necessary for the project.
  - [x] Users can track tickets in sprints and monitor things like burndown.
  - [x] Members of the public can submit feature requests or report bugs
- [x] Chat is live with the following conditions satisfied:
  - [x] Users can post messages to public channels (potentially with some restrictions applied).
  - [x] Users can send private messages to each other as well as view private and public channels.
  - [x] Users can reply to messages in a thread that other users can see.
  - [x] Users can use emojis to react to messages.
- [x] Wiki is live with the following conditions satisfied:
  - [x] At least 1 document has been added to the wiki (preferably the onboarding instructions for these tools)
  - [x] Without logging in, members of the public can see wiki documents.
  - [x] Users can see history of changes to all documents.
  - [x] Web analytics have been integrated into the wiki and administrators can report on unique users, page views, etc. - ticket that will be tracked in #1231 
- [x]  Contact us option is live with the following conditions satisfied
  - [x]  At least 1 inquiry has been received

**Comment by sumiat** [comment]
@widal001 - moved some of the DoD in this for shared calendar and document sharing into #61; not certain that's the appropriate place for it but I'm checking with @EOKENAVA too on some clear next steps/status of that work so we can see where they should live. 

for the wiki: i wasn't sure about the last bullet point around web analytics. maybe you can take look and mark this as closed based on that.

**Comment by widal001** [comment]
> for the wiki: i wasn't sure about the last bullet point around web analytics. maybe you can take look and mark this as closed based on that.

We should create a ticket for this! It's basically like a three step process:

1. Create a new data stream in Google Analytics and get a tracking ID
2. Install the [Google Analytics integration on our public wiki space](https://www.gitbook.com/integrations/googleanalytics) -- Note this does require Creator or Admin privileges on a space
3. Add the tracking ID to the dialogue box that pops up when installing the integration

**Comment by sumiat** [comment]
Thanks Billy! Added it. I'll check GA later to make sure it's working properly
