### ISSUE TITLE
[10k]: Delivery dashboard - Metrics

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#303]
### Description

Create a series of scripts that calculate key sprint and delivery metrics that we want to track within the project and publish on the delivery dashboard.

### Business goals

- Prioritize a series of metrics that help inform sprint planning and delivery management
- Create a series of reusable scripts that make it easier to calculate future metrics
- Provide a narrative explanation of how metrics are calculated, so that members of the public can understand the logic behind these metrics

### Sub-Tasks

Sub-tasks will be tracked in [this milestone](https://github.com/HHS/simpler-grants-gov/milestone/81)

### Acceptance criteria

- [ ] Project stakeholders can report on the following metrics:
  - [ ] Sprint completion -- # of tickets and/or points created vs planned per sprint
  - [x] Sprint burndown -- Total number of points remaining over the course of the sprint
  - [ ] Sprint burnup -- Total number of open and closed tickets per day in the sprint
  - [x] Deliverable completion -- % of tickets and/or points completed per deliverable
  - [x] Deliverable burndown -- Total number of points remaining over time for a given deliverable
  - [ ] Deliverable burnup -- Total number of open and closed tickets over time for a given deliverable
- [x] If any of the metrics above require custom code to generate, that code is stored in an `analytics/` sub-directory
- [ ] Each time new code is pushed to the `analytics/` directory the following code quality checks are run:
  - [ ] Linting
  - [ ] Auto-formatting
  - [ ] Type checking
  - [ ] Unit tests

**Comment by widal001** [comment]
This 10k ticket is being replaced by #41

**Comment by widal001** [comment]
We were planning to create a separate issue but decided to repurpose this one instead

**Comment by widal001** [comment]
Replacing our old 10k ft deliverable issues with a new Epic format

**Comment by widal001** [comment]
Reopening for review during sprint planning
