### ISSUE TITLE
Full Support for Opportunity Attachments (NOFOs) *

### ISSUE THREAD

**Issue by mxk0** [HHS/simpler-grants-gov#3045]
### Press release

We are excited to announce that the Simpler.Grants.gov modernization effort now includes all Notice of Funding Opportunity (NOFO) attachments for users viewing an opportunity. This feature enables users to review the full range of details about an opportunity and download the most-relevant NOFO document in a single click. Having this attachment foundation in place will also allow us to deliver application packages to users soon.

### Acceptance criteria

- [x] 95% of opportunity attachments available on existing Grants.gov are available on Simpler (#4009) - Completed Sprint 2.6
- [x] Attachment file storage in S3 is behind our CloudFront CDN
- [x] The URLs for attachments are permalinks, letting users share or bookmark the file as long as it isn’t deleted

### Metrics

- [x] At least 500 opportunity attachment downloads (#4245) - Completed Sprint 2.6
- [x] Usability testing indicates at least 75% of users are able to easily find opportunity attachments ([#3894](https://github.com/HHS/simpler-grants-gov/issues/3894))
- [x] Set a baseline for click-through rate from an opportunity listing to an opportunity attachment (#4244)

### Assumptions and dependencies

- There is a small but potentially high-impact risk that rolling out attachments will result in bad data or other broken functionality in prod. To mitigate this, we will have access to the kill switch that temporarily disables the opportunity listing page in place.
- Application package files are not in scope for this deliverable. This deliverable is only for NOFO files (i.e. files listed under “Related Documents” in the existing Grants.gov opportunity listing page). That said, we need to do some discovery on application package files to ensure our file storage architecture works for that category of files too.

**Comment by mdragon** [comment]
## Sprint 2.1 updates

**Status:** 🟢 On track

### Sprint goal

The main goal for this deliverable in Sprints 2.1 was to get an initial migration process built and manually running in the Dev environment

### Accomplishments

- Code is working and is being tested in lower environments

### Rollover

- N/A

### Risks

- Small risk - This data migration does represent a potentially lengthy run time, so we may have delays as stuff runs overnight, fails, we troubleshoot, push fixes, kick it off again, etc.
- Small risk - This data (the attachments) will be visible immediately on Opportunities in Prod as soon as they migrate. So we'll be doing very small batches and validating the attachments by hand, but it's possible broken attachment links or mis-linked attachments from other opportunities might appear briefly in Prod until corrected during early testing.

### Sprint 2.2 Goals

- Better develop the migration plan including the anticipated duration
- Further test the migration while scaling up the level of attachments being migrated in lower environments

**Comment by mdragon** [comment]
## Sprint 2.2 updates

**Status:** 🟢 On track

### Sprint goal
- Better develop the migration plan including the anticipated duration
- Further test the migration while scaling up the level of attachments being migrated in lower environments

### Accomplishments

- Manual job runs have imported a few hundred attachments into Dev

### Rollover
- Better develop the migration plan including the anticipated duration
- Further test the migration while scaling up the level of attachments being migrated in lower environments

### Risks

- Small risk - This data migration does represent a potentially lengthy run time, so we may have delays as stuff runs overnight, fails, we troubleshoot, push fixes, kick it off again, etc.
- Small risk - This data (the attachments) will be visible immediately on Opportunities in Prod as soon as they migrate. So we'll be doing very small batches and validating the attachments by hand, but it's possible broken attachment links or mis-linked attachments from other opportunities might appear briefly in Prod until corrected during early testing.

### Sprint 2.2 Goals
- Better develop the migration plan including the anticipated duration
- Further test the migration while scaling up the level of attachments being migrated in lower environments

**Comment by mdragon** [comment]
## Sprint 2.3 updates

**Status:** 🟢 On track

### Sprint goal
- Better develop the migration plan including the anticipated duration
- Further test the migration while scaling up the level of attachments being migrated in lower environments

### Accomplishments
- Ongoing testing of the migrations in Dev and adjustments to the code and configuration to allow stable execution.

### Rollover
- Better develop the migration plan including the anticipated duration
- Further test the migration while scaling up the level of attachments being migrated in lower environments

### Risks

- Small risk - This data migration does represent a potentially lengthy run time, so we may have delays as stuff runs overnight, fails, we troubleshoot, push fixes, kick it off again, etc.
- Small risk - This data (the attachments) will be visible immediately on Opportunities in Prod as soon as they migrate. So we'll be doing very small batches and validating the attachments by hand, but it's possible broken attachment links or mis-linked attachments from other opportunities might appear briefly in Prod until corrected during early testing.

### Sprint 2.4 Goals
- Finish the migration plan including the anticipated duration
- Finish migration of attachements in Dev

**Comment by mdragon** [comment]
## Sprint 2.5 updates

**Status:** 🟢 On track

### Sprint goal
- Prepare for Prod migration

### Accomplishments
- Files migrated in Stage
- Data scale and runtime evaluations completed

### Rollover
- n/a

### Risks

- Small risk - This data migration does represent a potentially lengthy run time, so we may have delays as stuff runs overnight, fails, we troubleshoot, push fixes, kick it off again, etc.
- Small risk - This data (the attachments) will be visible immediately on Opportunities in Prod as soon as they migrate. So we'll be doing very small batches and validating the attachments by hand, but it's possible broken attachment links or mis-linked attachments from other opportunities might appear briefly in Prod until corrected during early testing.

### Sprint 2.6 Goals
- Complete file migration in Prod

**Comment by lucasmbrown-usds** [comment]
Excited to see our plan to complete the file migration in PROD next sprint!

**Comment by mdragon** [comment]
## Sprint 2.6 updates

**Status:** 🟢 On track

### Sprint goal
- Complete file migration in Prod

### Accomplishments
- Files migrated in Prod
- 
### Rollover
- n/a

### Risks

- Potential risks did not manifest

### Sprint 2.7 Goals

- Build out support for tracking metrics to verify completion of this Deliverable.

**Comment by mxk0** [comment]
## Sprint 2.7 updates

**Status:** 🟢 COMPLETE

### Sprint goal
- Build out support for tracking metrics to verify completion of this Deliverable.

### Accomplishments
- Metrics tracked, dashboard created, Deliverable complete!

### Rollover
- N/A

### Risks

- N/A

### Sprint 2.8 Goals

- Future work on attachments will be included under #2875 and #4571.
