### ISSUE TITLE
Simpler Application Workflow *

### ISSUE THREAD

**Issue by mxk0** [HHS/simpler-grants-gov#3348]
### Press release

_Geared towards an internal HHS audience._

The Simpler team is excited to share the results of a successful round of discovery and scoping that puts us a big step closer to enabling users to apply for Federal funding opportunities on Simpler.Grants.gov. Through detailed interviews with HHS staff, Grants.gov’s contracting teams, and partner agencies, we created a comprehensive service blueprint showing both how applications flow through existing Grants.gov and how a user flow could work for applications going through Simpler. We also delivered a prototype application form with persistent data storage. Last but not least, we leveraged the service blueprint to define the scope of an Apply pilot for a small subset of applications we will process during Quad 3.

### Acceptance criteria

- [x] Service blueprint delivered showing the existing Grants.gov apply process and how a Simpler-only apply process could work ([#3803](https://github.com/HHS/simpler-grants-gov/issues/3803)). Includes data analysis on existing opportunities to answer questions like:
  - [x] What is the distribution of the number and type of forms used across opportunities? ([#3781](https://github.com/HHS/simpler-grants-gov/issues/3781)) 
  - [x] What is the distribution of the number of applicants across opportunities? ([#3782](https://github.com/HHS/simpler-grants-gov/issues/3782))
- [x] Prototype application with persistent data storage delivered with access restrictions (e.g. available via magic link) for use in applicant user research ([#3805](https://github.com/HHS/simpler-grants-gov/issues/3805))
  - [x] Includes engineering prototype de-risking whether we can read user <> org permissions from existing Grants.gov to determine whether a user has permission to apply for an opportunity #4259
- [ ] Julius and Lucas signed off on a plan to pilot 10 submitted applications (pilot to be executed in Quad 3) #4194

### Metrics

- [ ] At least 5 users participate in user research with the prototype application, eligible users are compensated for their time and expertise #4533 
- [x] Set a baseline metric of what percentage of all active opportunities could be supported by our planned application prototype #3810
- [x] Julius and Lucas sign off on a plan to support AuthZ in Simpler for 50% of users #4259

### Assumptions and dependencies

- A pilot will require finding an agency partner that has an opportunity with post and close dates within our pilot timeline.

**Comment by mxk0** [comment]
_Note: Sprint 2.3 is the first sprint with work on this deliverable._

## Sprint 2.3 Goals

- Kick off work with a team walkthrough of Deliverable scope
- Break the scope down into epics and rough tickets

**Comment by mxk0** [comment]
## Sprint 2.3 updates

**Status:** 🟢 On track

### Sprint goal

The main goals for this deliverable in Sprint 2.3 were to kick off work with a team walkthrough of the Deliverable scope and break the scope down into epics and rough tickets

### Accomplishments
- Work kicked off with a detailed [scope walkthrough](https://docs.google.com/document/d/1FTcMejdbGYRS37Afm_j416p5AyI7RZY7WrDVHnaavq4/edit?tab=t.0#heading=h.mtc4swvlio8d)
- Work broken down into epics and tickets under this Deliverable

### Rollover

- N/A

### Risks

- We don't see any large risks at this time.

### Sprint 2.4 Goals
-

**Comment by mxk0** [comment]
## Sprint 2.4 and 2.5 updates

**Status:** 🟢 On track

### Sprint goal

The main goals for this deliverable in Sprints 2.4 and 2.5 were to survey existing research surrounding Apply, run a workshop with HHS to validate some of our assumptions, and break down the work needed for our prototype into implementation tickets.

### Accomplishments
- Discovery on past user research complete
- Assumptions workshop with HHS complete
- Discovery on how existing Grants.gov extracts/ingests form PDFs complete
- Rough plan in place to ingest form PDFs into Simpler
- Implementation tickets created for application prototype database tables, API endpoints, and frontend

### Rollover

- N/A

### Risks

- N/A

### Sprint 2.6 Goals
- Apply service blueprint is drafted and shared internally with Nava/Focus team for feedback
- Database tables and API endpoints created for prototype

**Comment by mxk0** [comment]
## Sprint 2.4 and 2.5 updates

**Status:** 🟢 On track

### Sprint goal

The main goals for this deliverable in Sprint 2.6 were to share the apply current state service blueprint with the internal team for initial feedback and deliver the database tables and API endpoints needed for the apply prototype.

### Accomplishments
- Service blueprint shared with internal team
- Database tables and API endpoints available in local developer environment 

### Rollover

- N/A

### Risks

- N/A

### Sprint 2.7 Goals

- Contextual inquiry sessions completed with participants from the [Grants.gov](http://grants.gov/) applicant pool and the Co-Design Group, report complete
- Service blueprint current state finalized and shared with HHS, future state shared internally with Nava/Focus team for feedback
- Prototype frontend is feature complete on a developer machine and wired up to API endpoints
- Prototype process for converting form structures into Simpler data model complete
- Pilot plan drafted and shared with HHS for feedback

**Comment by mxk0** [comment]
## Sprint 2.7 update

**Status:** 🟢 On track

### Sprint goals

- Contextual inquiry sessions completed with participants from the [Grants.gov](http://grants.gov/) applicant pool and the Co-Design Group, report complete
- Service blueprint current state finalized and shared with HHS, future state shared internally with Nava/Focus team for feedback
- Prototype frontend is feature complete on a developer machine and wired up to API endpoints
- Prototype process for converting form structures into Simpler data model complete
- Pilot plan drafted and shared with HHS for feedback

### Accomplishments

- Contextual inquiry sessions completed with participants from the [Grants.gov](http://grants.gov/) applicant pool and the Co-Design Group, report started
- Service blueprint current state finalized and shared with HHS, future state shared internally with Nava/Focus team for feedback
- Prototype frontend is feature complete **in the lower environments** and wired up to API endpoints
- Prototype hallway usability testing and bug bash complete
- Prototype process for converting form structures into Simpler data model complete

### Rollover

- Contextual inquiry report complete
- Pilot plan drafted and shared with HHS for feedback

### Risks

- N/A

### Sprint 2.8 Goals

- Pilot plan drafted and shared with HHS for feedback (carryover from 2.7)
- Contextual inquiry sessions findings presented
- Future state service blueprint finalized and shared with HHS

**Comment by margaretspring** [comment]
## Sprint 2.8 update

**Status:** 
:large_yellow_circle: Pilot plan drafted and shared with HHS for feedback (rolling over to next quad)
:white_check_mark: Contextual inquiry sessions findings presented
:white_check_mark: Future state service blueprint finalized and shared with HHS
:white_check_mark: Prototype form live in Staging
:white_check_mark: Hallway usability testing with Apply prototype is complete

### Sprint goals

- Contextual inquiry report complete
- Pilot plan drafted and shared with HHS for feedback
- Future state service blueprint finalized and shared with HHS

### Accomplishments

- Contextual inquiry sessions completed with participants from the [Grants.gov](http://grants.gov/) applicant pool and the Co-Design Group, report started
- Service blueprint current state finalized and shared with HHS, future state shared internally with Nava/Focus team for feedback
- Prototype frontend is feature complete **in the lower environments** and wired up to API endpoints
- Prototype hallway usability testing and bug bash complete
- Prototype process for converting form structures into Simpler data model complete

### Rollover


### Risks

- N/A

### Sprint 3.1 Goals

- Contextual inquiry sessions findings presented

**Comment by mxk0** [comment]
The remaining work for this deliverable will be completed as part of #4572.
