### ISSUE TITLE
[10k]: API implementation v0

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#363]
### Description

During the [API Planning ](https://github.com/HHS/grants-equity/milestone/url)work we were able to formalize a series of architectural decisions about the API, including the technology stack and the type of API we will build, and the services we'll leverage to deploy and host it. This work focuses on implementing and building the API.

### Outcome
- We have an API that pulls at least one field and connects to the database

### Problems
- We need to understand the timing and scoping around test data
- Users and applications currently struggle to get the specific data they need and this allows us to understand how to make those use cases easier

### Dependencies
- [x] #139 

### Sub-Tasks
- [x] API in code (provides the endpoints) note: the API exists in code
- [x] Infrastructure - note: the infra is in place, dev and prod endpoints are available
- [x] #245  
- [x] #285 
- [x] #300 
- [x] Set up of logging 
- [x] Set up of metrics

### Definition of Done

- [x] The API pulls at least one specific field of data from the database
- [x] The API connects to the DB as intended 
- [x] The API is set up with logging and metrics to measure initial metrics
- [x] The API's performance and response times meet acceptable standards
