### ISSUE TITLE
[10k]: API logging and monitoring

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#370]
### Description

Set up logging and monitoring for the API so that we can monitor service availability and track API usage.

### Business Value & Goals

The purpose of this body of work is to:

- Enable the dev team to monitor service availability of the API and quickly troubleshoot issues that result in downtime
- Track overall API usage to understand and detect performance bottlenecks and resource constraints
- Support the collection of data used to calculate key metrics related to the API

### User Stories

- As a developer, I want:
  - the API availability to be continuously monitored, so that I can be alerted when there are service interruptions and attempt to troubleshoot this issue with minimal downtime for API consumers
  - to be alerted when the number (or percentage) of 4xx or 5xx response codes reach a certain threshold, so that I can investigate the source of these error codes and implement a fix if needed
  - the API logs to be retained for a certain period of time, so that I can search for patterns or check the history of certain API calls when an alert is triggered
  - to track operational metrics like response time, resource usage, etc. in an easy to use dashboard, so that I can identify performance bottlenecks or resource constraints
- As a product manager, I want to:
  - track the availability of the API over time, so that we can make sure we're meeting our SLAs
  - track data on the API calls, so that we can report on key project metrics about API usage

### Sub-Tasks

Sub-tasks can be found in [this milestone](https://github.com/HHS/simpler-grants-gov/milestone/101)

- [x] #710 

### Definition of Done

- [x] Logging has been set up for the API and: 
  - [ ] logs are retained for a specified period of time
  - [ ] logs can be filtered or searched for specific API calls and error messages
- [x] Monitoring has been set up for the API and:
  - [x] alerts are triggered when the API service is interrupted
  - [x] alerts are triggered when the number (or percentage) of 4xx and 5xx response codes reaches a certain threshold
- [ ] The data needed to report on operational metrics is captured and can be accessed programmatically

**Comment by sumiat** [comment]
We have logging set up in CloudWatch, we can document what exists.

**Comment by widal001** [comment]
Existing logging and monitoring alerts are described in [this GitBook page](https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/engineering/security/logging-and-monitoring)
