### ISSUE TITLE
[10k]: Comprehensive Incident Response

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#373]
### Description

Setup incident response alerts (through analytics services and logs) as well as escalation tools (such as PagerDuty).

Document incident response plan and coverage schedule. All individuals on the schedule are trained in incident response best practices.

### Dependencies

- [x] #57 
- [x] #370 
- [x] #53 

### Sub-Tasks

- [x] #413 
- [x] #414 
- [x] #415

### Definition of Done

- [ ] The incident response plan and on-call schedule is documented in a location that is accessible to all relevant stakeholders
- [ ] On-call staff are alerted when any critical service associated with the Grants.gov Modernization project is interrupted
- [ ] On-call staff have implemented the incident response plan in at least one training or simulation

**Comment by widal001** [comment]
Reopening for review during sprint planning
