### ISSUE TITLE
[10k]: Developer tools implementation

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#437]
### Description

Implement a set of developer tools that automate key code quality and security checks within the backend and frontend codebases.

### Dependencies

- [x] #50 
- [x] #42 
- [x] #49 

### Sub-Tasks

- [x] Documentation on how to get started with the tools selected in #50 
- [x] Onboard internal developers and maintainers
- [x] Onboard Open source contributors

### Definition of Done

- [ ] For all of the tools:
  - [x] Code required to configure and run the tools is deployed to `main` & PROD
  - [x] Instructions for how to adopt and use these tools is clearly documented in a public space
  - [x] At least 5 internal developers/maintainers have adopted and run these tools on a cloned version of the repo
  - [ ] At least 3 open source contributors have adopted and run these tools on a forked version of the repo - will be handled in #1231 
  - [x] ADRs documenting the selection of these tools and standards have been created and approved
  - [ ] #1333 - fast-follow ticket under #1231 
- [ ] **Automated testing framework** is live and meets the following conditions:
  - [x] At least 1 unit test has been added to the codebase
  - [x] At least 1 integration test has been added to the codebase
  - [x] Unit tests are run on every push to the remote GitHub repository
  - [x] Integration tests are run at least once before merging new code into `main`
  - [x] Code which fails any of the unit or integration tests will be blocked from merging into `main`
  - [x] A report on the percentage of code covered by tests is available after every test run
  - [ ] ~#1334~ will be handled separately
- [x] **Code quality checks** are live and meet the following conditions:
  - [x] All checks are run on every push to the remote GitHub repository
  - [x] The most important checks are run on every local commit
  - [x] Code which fails any of these checks will be blocked from merging into `main`
- [x] **Security checks** are live and meet the following conditions:
  - [x] At least 1 (test) security vulnerability report has been submitted
  - [x] Maintainers are notified within 1 hour of a vulnerability being reported within the grants API codebase
  - [x] Maintainers are notified within 72 hours of a vulnerability being reported on an upstream dependency
  - [x] Security checks are running on every push to the remote GitHub repository
  - [x] Code which fails any of these security checks is blocked from merging into `main`
- [x] **Dependency management** is live and meets the following conditions:
  - [x] At least 2 upstream dependencies have been added to the project
  - [x] Compatible versions of upstream dependencies are automatically detected when a new dependency is added
  - [x] Maintainers are notified when a new minor or major version of an upstream dependency is available
- [ ] **Config & secrets management** is live and meets the following conditions:
  - [x] At least 1 configuration variable has been added to the project
  - [x] This config variable has different values when it is running in different environments (e.g. dev, staging, and prod)
  - [x] At least 2 internal developers can access a shared value of this variable locally
  - [x] Developers can change the value of this config variable in their local environment without changing it for other developers
  - [ ] ~An integration test has been created to validate that this variable is injected at runtime~ - will be handled in #89

**Comment by sumiat** [comment]
Items that will be handled in other 10k/30k efforts: 
- #1334
- An integration test has been created to validate that this variable is injected at runtime #763 
- At least 3 open source contributors have adopted and run these tools on a forked version of the repo - will be handled in https://github.com/HHS/simpler-grants-gov/issues/1231
- https://github.com/HHS/simpler-grants-gov/issues/1333 - fast-follow ticket under https://github.com/HHS/simpler-grants-gov/issues/1231
