### ISSUE TITLE
[10k]: Setup recurring meetings

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#46]
### Description

Setup ongoing meetings that are necessary for delivery across all teams working on grants.gov and NOFO simplification. Example meetings include Team of Teams level meetings like planning, burndown check-in, demos, retros, office hours/open discussion slots, milestone planning, and team-building.

### Dependencies

None

### Sub-Tasks

- [ ] TODO

### Definition of Done

- [ ] [Milestone doc: Setup recurring meetings](https://github.com/HHS/grants-equity/pull/140)
- [x] Recurring meeting schedule established: Determine necessary meetings that need to take place for effective delivery across all teams - grants.gov and NOFO simplification. 
- [x] Meeting invites sent
- [x] Meeting agendas defined: prepare clear agendas for each recurring meeting, outlining the topics to be discussed and desired outcomes. 
- [x] Roles are set (facilitators, rotating MC, etc) 
- [ ] Team norming: continuously gather feedback from meeting participants to assess the effectiveness and value of the recurring meetings.

**Comment by EOKENAVA** [comment]
@widal001 - I'd like to discuss the strategy here. I know we currently have some meetings already set up on the Nava and Agile6 sides. Curious on how we can expand or better define those meetings

**Comment by sarahknoppA6** [comment]
This is pretty close to being done! There are a couple more meetings to get set up- I'm hoping this will be all finished by the time I am OOO on 9/14.

**Comment by sarahknoppA6** [comment]
I believe this still needs a milestone doc in order to be completed. Also, I think we should remove the sub-task of open source group kickoff from this ticket because that will be tied to the open source group kickoff milestone.

**Comment by sarahknoppA6** [comment]
This ticket should be discussed at the upcoming office hours. I believe it should be closed for now, or we should be scheduling team norms soon (because it keeps getting pushed due to competing priorities) and it can be closed at that time. We no longer need a doc for this one.
