### ISSUE TITLE
[10k]: GET Opportunities user research

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#513]
### Description

Conduct the user research needed to answer the open questions that were outlined in the GET Opportunities milestone doc.

### Questions

- Who are the primary consumers of the *current* API?
- What are the challenges with the *current* API and/or data model?
- How does the *current* API and/or data model contribute to problems with the UI?
- Who do we anticipate using the *new* API?
- How do consumers of the *new* API plan to use it?

### Stakeholders

- Current consumers of the endpoint
  - GrantSolutions
- Prospective users of the new endpoint
  - OpenGrants.io
  - USDR

### Sub-tasks

Sub-task(s) can be found in [this milestone](https://github.com/HHS/simpler-grants-gov/milestone/98)

- #646 

### Definition of Done

- [x] We have conducted at least one user research interview with all of the stakeholders listed above
- [x] Notes and/or key takeaways from these interviews have been stored in our Internal Wiki
- [x] Answers to all of the questions above have been documented in the GET Opportunities milestone doc

**Comment by sumiat** [comment]
There are some open questions that we'd like to explore. Documented here: https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/planning/product-roadmap/get-opportunities/api-opportunity-research
