### ISSUE TITLE
[10k]: Test data and schema

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#55]
### Description

Create a script or other automated tool that:

- Generates a database matching the schema of the beta.grants.gov core replica DB.
- Generates consistent fake example data that can be used for testing. (e.g., using the same random seed to generate consistent data, or saving test data values somewhere accessible)

### Business Value & Goals

The goal of this body of work is to:

- Dramatically speed up development because it will allow any developer to generate a local copy of the database that acts the same as the PROD beta.grants.gov database in their environment.
- Provide consistent input test data, so we can create reliable integration tests that look for expected and unexpected behaviors and prevent regression
- Enable us to quickly test the impact changes to the data model locally without having to run migrations in a shared dev or staging environment

### User Stories

As a developer I want:

- to be able to test changes I make to the data model locally, so that I can validate my code without depending on or connecting to a shared development environment
- to have a stable set of mock data that I can run my tests against, so that if my tests fail I know it's due to changes in the code and not changes in the underlying test data

### Dependencies

- [x] #48 
- [x] #42 
- [x] #50 

### Sub-Tasks

TODO

### Definition of Done

- [x] The codebase contains a script or set of fixtures that:
  - [x] Automatically generates a local copy of the database that serves the backend of the API
  - [x] Seeds the copy of the database with a consistent set of seed data
  - [x] Rolls back or blows away changes to the database made over the course of the tests
- [x] Changes to the schema made on a local development branch can also be tested in this copy of the database without having to manually run or rollback db migrations
