### ISSUE TITLE
[10k]: Measurement strategy

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#56]
### Description

Define and publish core project measurement strategy as a logic model and/or theory of change diagram.

### Dependencies

None

### Sub-Tasks

- [ ] [Docs]: Create Theory of Change diagram
- [ ] [Docs]: Create Logic Model diagram
- [ ] [Docs]: Create framework to categorize metrics

### Definition of Done

- [ ] A public-facing document has been published which contains the following contents:
  - [ ] A theory of change diagram for the Simpler Grants.gov initiative
  - [ ] A logic model for the Simpler Grants.gov initiative
  - [ ] A framework for grouping metrics within the project
- [ ] Previous milestones documents have been updated to categorize proposed metrics with this new framework
