### ISSUE TITLE
[10k]: Search UI - Create Initial Search Page

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#576]
### Description

Build the UI for the search page on simpler.grants.gov

### Business Value & Description

See: [Search UI public deliverable](https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/product/deliverables/specifications/search-user-interface#business-value).

### User Stories

See: [Search UI public deliverable](https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/product/deliverables/specifications/search-user-interface#business-value).

### Sub-Tasks

See https://github.com/HHS/simpler-grants-gov/milestone/134

### Definition of Done

- [x] Initial search page is available behind a feature flag. Functionality can be hidden from users behind a URL-based feature flag, if desired
- [x]  Code is deployed to main & PROD through our CI/CD pipeline
- [x] Services are live in PROD (maybe behind feature flag)
- [x] All new services have passed a security review (if necessary)
- [x] All new services have completed a 508 compliance review (if necessary)
- [x] Key architectural decisions made about this deliverable are documented publicly
- [x]  Users can search for opportunities by key word
- [x] Users can filter search results by at least one structured field (e.g. award date, opportunity type, etc.)
- [x] Users can sort search results by at least one structured field (e.g. award date, title, etc.)
- [x] Search criteria are reflected in the URL so that users can bookmark or share the link to the page with the results from that combination of criteria
- [x]  Users can access the corresponding grants.gov page for an opportunity they find on simpler.grants.gov via link on the search results

**Comment by widal001** [comment]
Replacing our old 10k ft deliverable issues with a new Epic format

**Comment by widal001** [comment]
Reopening for review during sprint planning
