### ISSUE TITLE
[10k]: Communication tools and open source repository configuration

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#61]
### Description

Configure the following things in the open source repository:

1. License
2. Responsible disclosure policy
3. Wiki (or link to wiki)
4. Contributions guide
5. Anti-deficiency act explainer
6. Paperwork reduction act explainer
7. Getting started guide (USDR runbook items) 

### Dependencies

- [x] #47 

### Sub-Tasks

- [ ] License
- [ ] Responsible disclosure policy
- [ ] Wiki (or link to wiki)
- [x] Contributions guide
- [ ] Anti-deficiency act explainer
- [ ] Paperwork reduction act explainer
- [x] #100 
- [ ] #118
- [ ] Sprint Retro ADR
- [ ] #412 
- [x] #410 
- [x] #409 
- [ ] Listserv implementation

#### Getting started guide and Contributions guide
- [x] #403 
- [x] #402
- [x] #416 
- [x] #419

### Definition of Done

- [ ] Calendar is live with the following conditions satisfied:
  - [ ] At least 1 event has been added
  - [ ] Without logging in, members of the public can see calendar events that are open to the public
  - [ ] Members of the public can copy events to their own calendar and/or RSVP to attend the event
- [ ] Video conference is live with the following conditions satisfied
  - [ ] At least one public meeting has been hosted
  - [ ] At least one public meeting has been recorded, with recording and transcript uploaded to the wiki
  - [ ] Users can join the call via video or phone
  - [ ] Users can access a live transcript during the video call
- [ ] Document sharing platform is live with the following conditions satisfied:
  - [ ] At least 1 document has been created and shared via the platform
  - [ ] At least 2 people have contributed to the document
  - [ ] Multiple users can collaboratively edit the document
  - [ ] Access to documents can be restricted to certain users or groups
  - [ ] Documents can optionally be shared with the public so that they can read it without logging in
- [ ] Sprint retro tool is live with the following conditions satisfied:
  - [ ] At least 1 sprint retro has been conducted with the tool
  - [ ] Users can create and assign action items from within the tool
- [ ] Email listserv is live with the following conditions satisfied
  - [ ] At least one email has been sent out to the listserv
  - [ ] Any member of the listserv can send emails to the entire listserv
  - [ ] Any member of the listserv can reply all to an email
  - [ ] Any member of the listserv can reply directly to an email sender
- [ ] Contact us option is live with the following conditions satisfied
  - [ ] At least 1 inquiry has been received

**Comment by widal001** [comment]
This is being tracked with a separate milestone.
