### ISSUE TITLE
[10k]: Feature flag framework

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#67]
### Description

Choose and implement a framework for hiding functionality behind feature flags in production.

### Business Value & Goals

The goal of this body of work is to:

- Decouple the deploy cycle from the release cycle
- Enable the team to expose or hide features without changing the underlying source code
- Support QA testing of features in production before rolling them out to all users
- Create the foundation for future A/B testing or targeted beta releases to subsets of users

### User Stories

- As a developer I want to:
  - expose or hide features without changing the underlying source code, so that we don't have to redeploy each time we want to toggle visibility
  - be able to temporarily expose new features for QA, so that I can test how code behaves in production without impacting the experience of everyone using the application 
- As a product manager, I want to:
  - decouple the deployment cycle from the release cycle, so that developers don't need to time their deploys to match communication around the release of certain features
  - hide or expose functionality based on certain conditions at runtime, so that we can conduct A/B testing of certain features or capabilities
  - expose new features to a targeted subset of users, so that they can test and provide feedback on those features before they are rolled out to everyone

### Dependencies

- [x] #44 

### Sub-Tasks

#368 

### Definition of Done

- [ ] Functionality can be hidden or exposed in production without changing the underlying source code - [documented in `documentation/api`](https://github.com/HHS/simpler-grants-gov/blob/main/documentation/api/feature-flags.md)
   - [x] It doesn't update live; can expand later
- [ ] Access to new functionality can be extended to a subset of users without releasing it to everyone using the application - [documented in `documentation/api`](https://github.com/HHS/simpler-grants-gov/blob/main/documentation/api/feature-flags.md)
    - [x] Can pass the header but no user by user approach

**Comment by acouch** [comment]
This wasn't scoped for the "Search UI 30K", moving to "Search 2.0" for now. We did add a limited feature flag for the frontend, but not as comprehensive of what is described here.

**Comment by acouch** [comment]
@widal001 do we want to keep this open or close it?

> Create the foundation for future A/B testing or targeted beta releases to subsets of users

We have met the criteria with the feature flag capability currently except the A/B testing.

**Comment by widal001** [comment]
Replacing our old 10k ft deliverable issues with a new Epic format
