### ISSUE TITLE
[Task]: Review and Create Plan for Security Controls in the "Physical And Environmental Protection" Control Family

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#672]
### Summary

Review the security controls in the “Physical And Environmental Protection” family and create tickets or a plan to respond to the controls given the inclusion of the simpler infrastructure.

### Acceptance criteria

- [x] Tickets and/or plan created for this control family

### Tasks noted
- [ ] Determine if Simpler needs same multi-zone failover capability
- [ ] Determine if "Contingency and Disaster Recovery Plan." needs to be updated

**Comment by acouch** [comment]
Tasks noted:

- [ ] Determine if "Contingency and Disaster Recovery Plan." needs to be updated
- [ ] Determine if Simpler needs same multi-zone failover capability.
- [ ] Determine if "Grants Program Solutions and Information Technology System Security Plan, Version 1.2" needs to be update
