### ISSUE TITLE
[10k]: API versioning framework

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#68]
### Description

Choose and implement a framework for versioning the API using semantic versioning that enables us to issue minor and major version updates to the API. Versions should also be documented in the API docs.

Also develop and execute release management plan with plan for release cycles, release notes, etc.

### Business Value & Goals

The purpose of this body of work is to:

- Enable the dev team to release major and minor version updates to the API in a way that is predictable for API consumers
- Establish a system for maintaining backward compatibility, while enabling consumers to opt in to breaking changes
- Establish a mechanism for communicating the changes being introduced in a given release and documenting the differences in API behavior based on the version that someone is using

### User Stories

As an API consumer, I want:
  - changes made to a given endpoint to be backward-compatible, so that I can start building against this API without worrying about breaking changes
  - to be able to specify which (major) version of the API I consume from, so that I can opt into a given version when I'm ready to handle breaking changes
  - to understand what changes are being made to the API in a given release, so that I can take advantage of new functionality or prepare my application to migrate to a new major version when I'm ready
  - to be able to read API documentation that is specific to the version of the API that I'm consuming, so that I know which functionality is available to me

### Dependencies

- [x] #42 

### Sub-Tasks

- #697 

### Definition of Done

- [x] The API implements a versioning framework that allows the dev team to release major and minor updates
- [ ] We've established a mechanism for documenting the changes that are introduced with each release
- [x] API consumers can specify which (major) version of the API they want to consume from in order to preserve backwards compatibility
- [ ] API consumers can read API documentation that corresponds to the version of the API they are using

### Open Questions / Notes

- As people start to subscribe to this API, are there ways that people can access the previous stable version instead of getting the most current version? How are we supporting backwards compatibility? 
- What should be done for the first release vs future releases? 
- We will publish these new changes and people can decide on whether they want to use that version
- ADR for the versioning framework (consider different versioning options, approvals: billy/lucas)

**Comment by widal001** [comment]
We decided to use path-based versioning for the API (at least for the initial launch) and will start with v0. The rationale and approach is described in the [repository documentation about API versioning](https://github.com/HHS/simpler-grants-gov/blob/main/documentation/api/api-versioning.md).

Tying API user guide and docs to API versioning is being descoped and addressed in a later deliverable.
