### ISSUE TITLE
[Task]: Rename milestones to deliverables in the repo

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#681]
### Summary

The term `milestones` is used in several places throughout the repository, mainly in `documentation/milestones/`. This folder and other references to `milestone` should be replaced with `deliverable`

### Acceptance criteria

- [ ] The following folders and files have been renamed:
  - [ ] `documentation/milestones/` --> `documentation/deliverables/`
  - [ ] `milestones/individual_milestones/` --> `deliverables/individual_deliverables/`
  - [ ] `milestones/milestone_template.md` --> `deliverables/deliverable_template.md`
  - [ ] `milestones/milestone_dependency_diagram.mmd` --> `deliverables/deliverable_dependency_diagram.mmd`
- [ ] References to the term `milestone` has been replaced with `deliverable` in all documents in those directories
- [ ] Links to any of the renamed files or folders have been updated
