### ISSUE TITLE
[Task]: Process page milestones section 

### ISSUE THREAD

**Issue by andycochran** [HHS/simpler-grants-gov#717]
### Summary

[Figma prototype](https://www.figma.com/proto/lpKPdyTyLJB5JArxhGjJnE/beta.grants.gov?type=design&node-id=918-1623&t=nFLaS0HsocPUQI8k-0&scaling=scale-down-width&page-id=918%3A1622&starting-point-node-id=918%3A1623)

<img width="607" alt="image" src="https://github.com/HHS/simpler-grants-gov/assets/409279/c2ac365b-80f6-4147-a92b-433c0e855832">

Links: 
- API link: https://github.com/HHS/simpler-grants-gov/issues/70
- Search link: https://github.com/HHS/simpler-grants-gov/issues/89

### Acceptance criteria

- [ ] Add milestones section
- [ ] Tests pass and there is a storybook component
- [ ]  Design will need to be responsive
