### ISSUE TITLE
[10k]: Static site - Communications and CTAs

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#749]
### Definition

Create a communications strategy for the public launch of the static site as well as future stakeholder engagement around the Simpler.Grants.gov initiative.

### Business Goals

- Share the site with the first round of public stakeholders
- Develop a communication strategy for ongoing stakeholder engagement

### In scope

- An email blast to the first set of stakeholders
- A long-term communications strategy document that describes plans for continued engagement of internal and external stakeholders 

### Out of scope

- Creating a feedback mechanism for stakeholders -- that's tracked in #596
- Launching the open source group -- that's tracked in #72 

- [ ] A longer-term stakeholder engagement plan has been drafted that answers the following questions:
  - [ ] Which stakeholder groups are we planning to engage?
  - [ ] Who is responsible for managing the relationship with each group?
  - [ ] What is the primary channel and cadence for those communications?

### Tasks

Sub-tasks can be found in [this milestone](https://github.com/HHS/simpler-grants-gov/milestone/92)

### Definition of Done

- [x] An email has been sent out to the subset of public stakeholders with whom we plan to share the static site
- [x] Key internal stakeholders (e.g. help desk staff, HHS leadership) have been notified when the email is sent out so that they can prepare for questions from public stakeholders

- [x] Help Desk is notified and trained for any potential support issues that may come through
