### ISSUE TITLE
[10k]: Static site - Infrastructure improvements for public launch

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#751]
### Definition

Make the necessary updates to the static-site infrastructure needed to support the traffic anticipated with the public launch. 

**Note:** the initial outreach is expected to include about 1,000 stakeholders, so the initial upper limit we should expect for traffic is around 1,000 concurrent users. However, as these stakeholders begin to share the site, it may result in higher levels of site traffic.

### Business Goals

- Create the systems and processes needed to support the heavier site traffic anticipated with the public launch.
- Build trust in the modernization effort with early adopters by ensuring that the site remains available and responsive when they visit it.

### In scope

- Switching the Next.js rendering strategy from server side rendering (SSR) to static site generation (SSG)
- Setting up a CDN (or other caching strategy)
- Setting up lightweight load testing

### Out of scope

- Setting up an automated performance testing framework -- that's tracked in #69 

### Tasks

- [ ] {Link to tasks that should be completed with this deliverable}

### Definition of Done

- [ ] Site has been load tested to simulate 1,000 concurrent users
- [ ] Strategies have been adopted to increase the reliability and performance of the static site
