### ISSUE TITLE
[Task]: Launch checklist

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#753]
### Summary

**Launch checklist**

Use this launch checklist to create tickets to track launch activities required for the static site launch to the public. 

Communications
- [x] Draft email communications to release audience - #707 
- [x] Content added under Simpler Grants.gov Brand in Sendy - #708 
- [ ] Email draft to audience approved by HHS and approver list - #707 
- [ ] Email draft scheduled to be sent on intended date - #817 
- [x] Stakeholder engagement plan - deck to share with notified stakeholders

Help Desk
- [x] Help desk transcript updated https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/collaborating/launch-checklist/static-site-public-pre-launch-checklist/help-desk-faqs - #706 
- [ ] Help desk FAQs shared and reviewed with the Support team 

Analytics
- [x] Site analytics set up in Google Analytics (optional, as standard tracking comes with GA) - not needed
- [ ] Test Google Analytics to ensure tracking is setup - #701 

Engineering
- [x] Load testing to handle expected audience - #696 
- [ ] Tabletop exercise to test incident response - #700 

Front-end
- [ ] Bug bash testing (optional) 
- [ ] 508 compliance review (optional) 

Security
- [x] Security review process completed for launch
