### ISSUE TITLE
[Task]: Configure Current SSO for Simpler users

### ISSUE THREAD

**Issue by acouch** [HHS/simpler-grants-gov#798]
### Summary

The current SSO and user account management in place for the grants.gov AWS environments needs to be extended for the Simpler AWS environments.

#### Sub-tasks

- [ ] Compile Simpler Team personnel list for AWS SSO/JumpCloud OpenVPN

### Acceptance criteria

- [ ] A small majority of the team has setup SSO
- [ ] A small majority of the team has setup the VPN
- [ ] Existing Simpler AWS users removed
- [ ] Simpler engineers authenticated and properly permissioned for Simpler AWS accounts
- [ ] AWS user management documentation updated

**Comment by shawnsheckler** [comment]
Shane marked the Jira ticket as completed on 15 February.

**Comment by coilysiren** [comment]
This is done on the Simpler side now
