### ISSUE TITLE
[10k]: Search API - API development

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#90]
### Description

1.0 version of an API to provide better searching on opportunities.

### Dependencies

- [x] #70 

### Sub-Tasks

Work is under this [milestone](https://github.com/HHS/simpler-grants-gov/milestone/132)

### Definition of Done

- [x] Search API model uses the new schema and fields
- [x] Database schema for the opportunity tables has been updated
- [x] The search API endpoint has been expanded to meet the database expanded data model defined in #973 
- [x] Database tables for the expanded data model have been added
- [x] Lookup value logic within the API has been setup
- [ ] Additional fields to the API such as "order_by" has been added
- [ ] Query filtering to the search endpoint has been added
- [ ] Logging of extra parameters has been updated
- [ ] A new (minor) version of the GET /opportunities API endpoint has been released and includes fields from the expanded data model (e.g. status, agency, etc.)
- [ ] A new search endpoint has been released that allows API consumers to: 
- [ ] Search for opportunities by keyword
  - [ ] Filter opportunities by at least one structured field from the new data model
  - [ ] Sort opportunities by at least one structured field from the new data model

Nice to have
- [ ] S2S users can sign up for the API with a self-service authentication option that replaces the key management method established previously
- [ ] S2S users can learn how to consume from the API by following a publicly documented user guide, in addition to referencing our OpenAPI specification

**Comment by widal001** [comment]
Replacing our old 10k ft deliverable issues with a new Epic format

**Comment by widal001** [comment]
Reopening for review during sprint planning
