### ISSUE TITLE
[10k]: Search API - Communications for limited outreach

### ISSUE THREAD

**Issue by sumiat** [HHS/simpler-grants-gov#942]
### Definition

Create and manage the communications needed to support a targeted announcement to key stakeholders about the Search API (#972) 

### Business Goals

- Keeping internal stakeholders informed about upcoming releases prior to announcing them to external partners
- Beginning to invite trusted system-to-system partners to test and provide feedback on the first version of our new Search API

### In scope

- Preparing a presentation or updates to key internal stakeholders about this release
- Drafting and approving communications for a limited outreach to trusted external partners

### Out of scope

- A public announcement or email blast to all of the members on our listserv. This deliverable will _only_ be announced to a subset of trusted partners.

### Tasks

- [ ] {List the tasks that should be completed with this deliverable}

### Definition of Done

- [ ] The following internal stakeholders have been notified about the Search API prior to making a limited announcement to external stakeholders:
  - [ ] TODO
- [ ] The content of the limited announcement has been approved by the following stakeholders
  - [ ] TODO
- [ ] A limited announcement (most likely email) has been set to _trusted_ members of the following stakeholder groups inviting them to test out our new API:
  - [ ] [GrantSolutions](https://home.grantsolutions.gov/home/)
  - [ ] [US Digital Response (USDR)](https://www.usdigitalresponse.org/)
  - [ ] [OpenGrants.io](https://www.opengrants.io/)
  - [ ] Subset of the [Federal Demonstration Partnership (FDP)](https://thefdp.org/)

**Comment by sarahknoppA6** [comment]
In P&D office hours, discussed scoping this into a different 30k in order to keep the current GET Opps 30k really focused on getting from 0 to 1. @sumiat @widal001

**Comment by widal001** [comment]
Replacing our old 10k ft deliverable issues with a new Epic format

**Comment by widal001** [comment]
Reopening for review during sprint planning
