### ISSUE TITLE
[10k]: Search API - Expanded data model

### ISSUE THREAD

**Issue by widal001** [HHS/simpler-grants-gov#973]
### Definition

Expand the data model in the new Postgres database beyond the single opportunity table.

### Business Goals

- Enable the team to build future endpoints against a simplified data model instead of one that is tightly coupled to the existing schema in grants.gov live
- Create the foundation for expanding beyond the existing `opportunity` table, which will be useful for things like search

### In scope

- Propose an approach for the data model that will be reviewed by key stakeholders such as Narmada, Lucas, and Julius
- Investigation into current database structure
- Determine data conversions that will be needed

### Out of scope

- {Item that is out of scope for this work}

### Tasks

- [x] Proposal for approach on data model and cleanup
- [x] Research/discussion around data model session
- [x] Investigation of table duplication issues
- [x] Incorporate suggestions into data model approach
- [x] History table investigation
- [x] Determine data conversions required for ETL prep work

### Definition of Done

- [x] The API reads data from a new opportunity data model with clearly defined tables, relationships, and attributes
- [x] The API pulls data from more than just the opportunity data of the Grants.gov live database. 
- [x] An ERD for the new data model is documented in a publicly accessible location, and the ERD is automatically updated with future changes to the data model

**Comment by sumiat** [comment]
- The API reads data from a new opportunity data model with clearly defined tables, relationships, and attributes: Based on data model discovery and proposal that was reviewed with key stakeholders. Documented here: https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/v1V0jIH7mb7Yb3jlNrgk/engineering/learnings/opportunity-endpoint-data-model
- The API pulls data from more than just the opportunity data of the Grants.gov live database: The API pulls data from more than opportunity table data from the g.gov replicated db
-  An ERD for the new data model is documented in a publicly accessible location, and the ERD is automatically updated with future changes to the data model: https://github.com/HHS/simpler-grants-gov/blob/main/documentation/api/database/erds/README.md#full-schema

**Comment by sumiat** [comment]
Updated in the implementation log section in: https://app.gitbook.com/o/cFcvhi6d0nlLyH2VzVgn/s/Pm7UEzeiS1tbLCV1SFRu/product/deliverables/specifications/search-api
